### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by satyamTiwary** [lefticus/cpp_starter_project#120]
Adding docker support would make the developer environment expected by this starter project portable. 

Setting up all the various executables expected by the cmake file is a little bit of a hinderance to productivity when setting up.

**Comment by ddalcino** [comment]
That's a good idea. I think I can do that; most of the work is already done in the CI builds. Give me a minute...

**Comment by ddalcino** [comment]
Apparently, there was already a dockerfile in #99, but you would never know that from the title of the PR. I haven't tried it.
