### ISSUE TITLE
Fix Apple Clang compiler string to set right set of compiler warnings

### ISSUE THREAD

**Issue by dhruvkakadiya** [lefticus/cpp_starter_project#23]
With MacOS Mojave(10.14.6) and `Apple clang version 11.0.0 (clang-1100.0.33.17)`, compiler string is `AppleClang` so same string needs to be used [here](https://github.com/lefticus/cpp_starter_project/blob/d7a2b6b891d75edc68c9d88dca7e24cd73e378b8/cmake/CompilerWarnings.cmake#L82). Though not sure if it's different per Mac OS version.

**Comment by ddalcino** [comment]
This appears to be addressed by PR #18

**Comment by dhruvkakadiya** [comment]
yes, thank you.

**Comment by dhruvkakadiya** [comment]
Sorry close this once it's been merged to `master`.

**Comment by dhruvkakadiya** [comment]
It's been fixed and merged with https://github.com/lefticus/cpp_starter_project/pull/18
