### ISSUE TITLE
How does project_warnings and project_options get included?

### ISSUE THREAD

**Issue by acgetchell** [lefticus/cpp_starter_project#29]
I am not understanding how:

```
# Link to project_options library to set compiler and sanitizer options
add_library(project_options INTERFACE)
target_compile_features(project_options INTERFACE cxx_std_17)

# Link to project_warnings library to set compiler warnings
add_library(project_warnings INTERFACE)
include(cmake/CompilerWarnings.cmake)
set_project_warnings(project_warnings)
```

Sets options on the project. The two "libraries" don't appear to be linked in anywhere, at least, that's how it appears in my project.

**Comment by ddalcino** [comment]
According to cmake documentation for [add_library](https://cmake.org/cmake/help/v3.0/command/add_library.html), when you make a library with `add_library(<name> INTERFACE)`, it makes an interface target that has properties but no build output. Later on, this library can be linked to an executable by calling `target_link_libraries`.

I agree that it is a little confusing that these two libraries are not linked to anything in the file in which they are defined. However, the CMakeLists.txt in the root directory calls `add_subdirectory` on three locations that will consume these libraries.

If you look in [fuzz_test/CMakeLists.txt](https://github.com/lefticus/cpp_starter_project/blob/master/fuzz_test/CMakeLists.txt), [test/CMakeLists.txt](https://github.com/lefticus/cpp_starter_project/blob/master/test/CMakeLists.txt), and [src/CMakeLists.txt](https://github.com/lefticus/cpp_starter_project/blob/master/src/CMakeLists.txt), you will see both `project_warnings` and `project_options` consumed by `target_link_libraries`. They are linked to every executable that the project builds.

**Comment by acgetchell** [comment]
Perfect, thanks for the clarification!
