### ISSUE TITLE
CLion build fails

### ISSUE THREAD

**Issue by NicolasIriarte** [lefticus/cpp_starter_project#31]
Maybe a newbie question but. Any ideas why building with CLion throw links errors, but manually not? I missing some extra-configuration on the CLions side?

**Comment by ddalcino** [comment]
If you can build the project using cmake from the terminal, but you cannot build it from Clion, that implies that Clion is mis-configured. Without a specific error message, it's impossible to know for sure.

Maybe someone can give a better answer at the [Clion forums](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200363649-CLion)?

**Comment by ddalcino** [comment]
Were you able to solve this issue?

Would it be appropriate to mark this issue “closed”?

**Comment by NicolasIriarte** [comment]
I can't fix the issue but the project works fine when is build/compiled from command-line. So (As you say) there must be a CLion problem. I will close the issue cause is not related to the project.
