### ISSUE TITLE
How to pass conan flags to cmake?

### ISSUE THREAD

**Issue by pkubik** [lefticus/cpp_starter_project#32]
There are some utilities to parse command args but I have no idea how to use them. Any ideas?

**Comment by ddalcino** [comment]
Are you trying to add additional Conan packages into your project? If so, there are two things you need to do:

1. Pass the name and version of the package into the `conan_cmake_run` command, which is called in `cmake/Conan.cmake`.
2. Make sure that your target executable is linked to that package by using the `target_link_libraries` command.

You will probably find it useful to look at how this project pulls in `sdl2` as a dependency. If you grep on every instance of `sdl2` in the project, you'll see the string `sdl2/2.0.10@bincrafters/stable` being added to the `CONAN_EXTRA_REQUIRES` variable in `CMakeLists.txt`, which is then passed as an argument into conan in `cmake/Conan.cmake`. You will also see `CONAN_PKG::sdl2` being linked to the executable in `src/sdl/CMakeLists.txt`.

Keep in mind that in CMake, every time you call `add_subdirectory(<some_subdirectory>)`, you are including the file `<some_subdirectory>/CMakeLists.txt`. Also, when you call `include(<some_path_to_a_file>)`, you are including all the CMake code in that file. You need to follow every inclusion to see what CMake is doing.

Hope that helps.

**Comment by pkubik** [comment]
I was thinking about flags that are specific to the user's machine. E.g. `--profile=my_clang_profile` or `--build=never` for debugging.

**Comment by ddalcino** [comment]
Check out the README.md at https://github.com/conan-io/cmake-conan for documentation on how to use the `conan_cmake_run` command.

I think you want `conan_cmake_run(... ...  PROFILE my_clang_profile BUILD never)` for those particular arguments.

**Comment by pkubik** [comment]
Thank you, that's exactly what I was looking for.

I've added `CONAN_PROFILE` option to my CMake with an empty string as default.

```
set(CONAN_PROFILE "" CACHE STRING "Conan profile to use (i.e. conan's --profile option")

conan_cmake_run(
  REQUIRES
  ${CONAN_EXTRA_REQUIRES}
  # ...
  PROFILE ${CONAN_PROFILE}
endmacro()
```

I think that's the way to go if anyone had the same problem. I've checked that the default behavior of not passing any `PROFILE` is preserved if the `CONAN_PROFILE` option is set to an empty string.
