### ISSUE TITLE
Any Reason to Not Use /permissive- for the MSVC Compiler Flags?

### ISSUE THREAD

**Issue by DeveloperPaul123** [lefticus/cpp_starter_project#38]
Are there arguments against using `/permissive-` for MSVC projects?

**Comment by ddalcino** [comment]
I don’t have any experience with this, but I just had a look at the documentation for that option(https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019), and it sounds like a great thing to add. It fits so well with the spirit of this project that I can’t see any good reason not to add it. I vote that you make a PR!

**Comment by DeveloperPaul123** [comment]
Thanks for the feedback! I'll file a PR then and hopefully it gets merged.

**Comment by Edhebi** [comment]
Can probably be close since the PR was merged
