### ISSUE TITLE
Issues with sdl installing through conan

### ISSUE THREAD

**Issue by ItsChoudhry** [lefticus/cpp_starter_project#79]
I enabled sdl and tried to build it and installing through conan throws a bunch of errors asking for packages that need to be installed like `libxcb-xkb-dev` and a bunch more. Other libraries with spdlog installed gracefully. Maybe it's something wrong with my machine? it's a clean ubuntu 20 build

Actually, After giving up trying to get sdl to work through conan I tried getting im-gui sfml to work and it also has similar dependency problems.

**Comment by ddalcino** [comment]
I’m sorry to hear you’re having trouble, but this is the expected behavior on Linux. Conan gets you the header files for the SDL and SFML, but not the binaries; you need to get those with your system package manager. Unfortunately, the process for doing so is a little different on each distro. You need to read the documentation for those libraries to find out how to do that.

Maybe the README should tell you how to install those libraries. I started to do that when I wrote that section of the README, but I gave up when I realized I would have to test my instructions on lots of Linux distros, and left links to the appropriate documentation instead.

If you think you can help improve the README on this issue, please file a PR!

**Comment by ItsChoudhry** [comment]
Yeah, I installed it manually in the end overall I find this super useful on getting on the right path. I would love to help! so the idea is the READ.md just needs a quick warning to say the libraries may not be installed correctly through conan and will need to be installed separately by reading the documentation of the libraries or google?

**Comment by ItsChoudhry** [comment]
This is this [guide]( https://gist.github.com/BoredBored/3187339a99f7786c25075d4d9c80fad5) I used to install SDL. Then you just need to remove the CMake stuff around Conan to download it and replace `CONAN_PKG::sdl2` to `SDL2` case sensitive. This worked on my build of ubuntu 20 and it works on ubuntu 18. The problem is it would be hard to make the readme bulletproof around every OS and I didn't read most of the readme (which is poor on my part as it's written very well) you clearly explain this point. I guess I'll close this and sorry.

**Comment by ddalcino** [comment]
Glad you got it working!

**Comment by ddalcino** [comment]
I remembered this really wrong. The Conan package does get you all of SDL; what it doesn't get you is all of SDL's dependencies. Those dependencies are `libxcb-xkb-dev`, etc. I don't know why Conan can't or won't get those for you. I had assumed that they were specific to each distro or window-manager; I could be wrong. 

However, if you run CMake, Conan will tell you what dependencies are missing, and if you install all of them with your package manager, everything will build properly. I don't know how to get Conan to tell me what all my OS-specific dependencies are all at once, so I had to 1) run CMake, 2) read the error message, 3) install dependency listed in the error message, 4) repeat the previous 3 steps until the error messages go away. It's really tedious and really annoying. 

This is the full list of what I had to install on Fedora 31:

		libfontenc-devel
		libXaw-devel
		libXcomposite-devel
		libXcursor-devel
		libXdmcp-devel
		libXft-devel
		libXtst-devel
		libXinerama-devel
		xorg-x11-xkb-utils-devel
		libXres-devel
		libXScrnSaver-devel
		libXvMC-devel
		xorg-x11-xtrans-devel
		xcb-util-wm-devel
		xcb-util-image-devel
		xcb-util-keysyms-devel
		xcb-util-renderutil-devel
		xkeyboard-config-devel
		gdm-devel
		jack-audio-connection-kit-devel
		nas-devel

I only had to install 2 or 3 packages to get SFML working, but I don't remember what they were.

The packages have different names on different package managers, but Conan's error messages tell you exactly what they are called on your system. If Conan can figure out that much, there should be a way to query Conan for what you need to install yourself, but I haven't found it yet. There has got to be a better way to get SDL/SFML running with Conan than this.

**Comment by ItsChoudhry** [comment]
Yeah if there was a command to get all of the dependencies in one go that would be nice and be a depend workaround.
