### ISSUE TITLE
Question: linked libraries differences

### ISSUE THREAD

**Issue by ascii78** [lefticus/cpp_starter_project#83]
This is a question, everything is working functionally.

I've compiled the cpp starter and a few episodes of the game, I was interested in how one would package it between distributions and how header only/shared libraries/included libraries work. Everything compiles and is functionally fine, but the ldd output seems very different. Does anyone know where the differences come from, is that distribution specific or maybe something in conan ?

(left ubuntu/right arch)

![image](https://user-images.githubusercontent.com/1138654/90677368-95b93400-e25d-11ea-9a68-e10fe79796ef.png)

**Comment by ddalcino** [comment]
That's a really good question. Are you using the same compiler/version on both Ubuntu and Arch? I wouldn't expect that to account for such a huge difference, but it might be a hint.

Personally, I have used [AppImages](https://appimage.org/) to package software for Linux. You could also look into Flatpaks and Snaps: there are various technological and ideological debates regarding which packaging solution is best. All three solutions will package your application into an archive that has its own directory structure, and that structure includes most, if not all, of the shared objects that your program needs to run. AppImages have their own `/usr/lib/` directory that contains shared objects. When the dynamic linker loads your program and shared objects at runtime, it first looks for shared objects within the AppImage directories. If they don't exist within the AppImage, the linker will look for them in their usual locations.

We've been building AppImages using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) for a few years now, and we've been very happy with the results. We've been using a Docker image of Ubuntu 14.04 LTS for builds. LTS 14 is ancient, but it builds AppImages that run properly on every Linux distro we've tried: this was definitely not the case when building on anything newer. We use a script that runs acceptance tests on our built AppImage on 5 different QEMU virtual machines running different distros. This setup doesn't give us complete coverage for every Linux distro, but each of the distros we test are upstream of a whole lot of other distros, and that's been good enough for us so far.

You certainly don't need to take the AppImage-style approach to deployment. There should be plenty of guides online for developing a .rpm, .deb, or a PKGBUILD for Arch if you want to submit packages to DNF, APT or the AUR. For us, the AppImages looked like a lot less work.

**Comment by ascii78** [comment]
Maybe others find this interesting so I'll just post my findings, it seems an interaction between conan and arch/ubuntu. I've created a copy of the template with the third party libraries included instead of using conan. This resulted in less dependencies. It seems conan introduces the linking to libxcb for example, this is because sfml depends on conan x11 which points to the systems x11. However conan has a bit of a shotgun approach including every x11 dependency possible so it doesn't miss anything. The is both the same on arch and ubuntu, the interesting thing is that the result in the screenshot comes from the fact that ubuntu filters out what is not actually needed by using the linker option `--as-needed` (man ld). by default. This is not the case in arch, so if conan tells it to link to everything it will link to everything. See example below with small c file on both distributions. 

```c
#include <stdio.h>
// don't use anything
int main() {
	return 0;
}

```

```bash
gcc   -Wl,--no-as-needed -lxcb-icccm -o hello-no-as-needed hello.c 
echo "no-as-needed"
ldd hello-no-as-needed

gcc   -Wl,--as-needed -lxcb-icccm -o hello-as-needed hello.c
echo "as-needed"
ldd hello-as-needed

gcc   -o hello-default hello.c -lxcb-icccm  
echo "hello-default"
ldd hello-default
```

```
# results for arch
no-as-needed
	linux-vdso.so.1 (0x00007efd63fc3000)
	libxcb-icccm.so.4 => /usr/lib/libxcb-icccm.so.4 (0x00007efd63f70000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007efd63da7000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007efd63d7d000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007efd63fc5000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007efd63d78000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007efd63d70000)
as-needed
	linux-vdso.so.1 (0x00007ffda2df7000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fee151a3000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fee153b5000)
hello-default
	linux-vdso.so.1 (0x00007ffeaf6e7000)
	libxcb-icccm.so.4 => /usr/lib/libxcb-icccm.so.4 (0x00007fa366cc0000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa366af7000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fa366acd000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa366d0f000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fa366ac8000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fa366ac0000)
```


```
# results for ubuntu
no-as-needed
	linux-vdso.so.1 (0x00007ffc945d4000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007f4f007d6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4f005e4000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4f005ba000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4f007fb000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4f005b4000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4f005ac000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4f00592000)
as-needed
	linux-vdso.so.1 (0x00007fff6ce64000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd368802000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd368a12000)
hello-default
	linux-vdso.so.1 (0x00007fff1a9f4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f990682c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9906a3c000)
```

Note that all packages compiled for arch do have --as-needed enabled specifically, this is just a bare commandline thing.

Regarding AppImage, I've also looked at it a few days ago since I was curious about packaging on older distributions, particularly ubuntu 16.04. A few observations:

- Using conan probably won't work since it's defaulting to python3 soon, I've not verified this though.
- Other convenient options like cmake fetchcontent require newer cmake.
- Best to include 3rdparty libs inside your source tree, but this is a lot of work vs conan etc.
- AppImage docs say to use the compiler from 16.04 (or the older distribution you want to use), this will require
you to use an older C++ version (C++11,C++14 etc). As I'm following along with the game tutorial, It will probably
make use of some newer C++ techniques.

**Comment by ascii78** [comment]
Oh, also,

To specifically add --as-need linker option add for example:

target_link_options(game PUBLIC "LINKER:--as-needed")

to src/CMakeLists.txt (since cmake 3.13)

**Comment by ascii78** [comment]
"Using conan probably won't work since it's defaulting to python3 soon, I've not verified this though."

Oops, no, conan uses python **3.5** which is installed on 16.04, so it works just fine there, comment on C++ versions still hold though.

Also see. https://repology.org/project/python/versions
