### ISSUE TITLE
README.md calls for an in-source build

### ISSUE THREAD

**Issue by ddalcino** [lefticus/cpp_starter_project#87]
A recent commit (b0edb4b4826510f9d0bdd136d51100d5d73d75f3) added code that causes the build to fail if CMake detects an in-source build.

The [ccmake directions in the README](https://github.com/lefticus/cpp_starter_project#configure-via-ccmake) unambiguously tell you to run the configuration in the source directory, not the build directory. I tried following these directions, and they trigger a fatal error due to the in-source build. I think the documentation needs to be updated so that it doesn't guide new users directly into this fatal error.

**Comment by lefticus** [comment]
Fixed in cac3864273c55e45950b859e4173dde9a402cbc6
